name: Test and release

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
 pull_request:
 push:
  branches: [ master ]

jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [12.x]
  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}
  - name: Install
    run: |
      npm install
  - name: Test
    run: |
      npm test

 release:
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  needs: [test]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 12.x
  - name: Install
    run: |
      npm install
  - name: Release
    run: |
      npx semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
