name: Release and Publish

on:
 pull_request:
 push:
  branches: [ master ]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: 16.x
  - name: npm install
    run: |
      npm install -ws
  - name: npm test
    run: |
      npm test -ws
 release:
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  needs: [test]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: 16.x
  - name: npm install
    run: |
      npm install
  - name: npx semantic-release
    run: |
      npx semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
